version: 2.1
# TODO: build, test and push java images API and background to to public Docker registry

# Terraform/Ansible is taken care of from our local machine
# Since this is a public repo, we don't want to expose Terraform outputs
# In a closed source env this would be different

# The live testing will be done from our local machine,
# since we need public DNS names from the EC2 instances outputted by Terraform