# Application Properties
application:
  outbox-relay:
    initial-delay: 30s
    fixed-delay: 15s
  notification:
    enabled: false
  scheduler:
    enabled: true
    initial-delay: 30s
    fixed-rate: 15s
    fixed-delay: 15s
    cron: "@weekly"
# Tomcat Server Properties
# https://docs.spring.io/spring-boot/how-to/webserver.html
server:
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: "application/json"
  ssl:
    enabled: false
  # Tomcat supports both H2 (Http2 w TLS) and H2C (Http2 without TLS)
  http2:
    enabled: true
# Spring Properties
spring:
  application:
    name: spring-crud
  web:
    resources:
      # No need to serve static resources as a REST API
      add-mappings: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: true
        serialization-mode: via_dto
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: true
      file: ${user.dir}/infrastructure/local/compose.yaml
      skip:
        in-tests: true
      start:
        skip: if_running
  datasource:
    hikari:
      pool-name: spring-crud-hikari-pool
      maximum-pool-size: 10
  jpa:
    properties:
      # pretty print SQL statements
      hibernate.format_sql: true
      # generate JDBC statistics
      hibernate.generate_statistics: true
      # batching
      hibernate.jdbc.batch_size: 50
      # batch when doing inserts
      hibernate.order_inserts: true
      # batch when using @Version
      hibernate.batch_versioned_data: true
      # batch when doing updates
      hibernate.order_updates: true
    hibernate:
      ddl-auto: create
    show-sql: true
    # Detach JPA from the Spring HTTP request lifecycle
    open-in-view: false
# Logging Properties
logging:
  level:
    root: INFO
# Actuator Properties
management:
  endpoints:
    web:
      exposure:
        include: "health, scheduledtasks, task, outbox"
# SpringDoc Properties
springdoc:
  show-actuator: true
  cache:
    disabled: true
