spring:
  application:
    name: spring-crud
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: true
      file: ${user.dir}/infrastructure/local/compose.yaml
      skip:
        in-tests: true
  datasource:
    hikari:
      pool-name: spring-crud-hikari-pool
      minimum-idle: 5
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.generate_statistics: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    # https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
    open-in-view: false