# Application Properties
application:
  outbox-relay:
    initial-delay: 10s
    fixed-delay: 5s
    cleanup: 60s
  scheduler:
    enabled: true
    initial-delay: 30s
    fixed-rate: 15s
    fixed-delay: 15s
    cron: 0 0 0 * * *
# Spring Properties
spring:
  task:
    scheduling:
      thread-name-prefix: "scheduler-"
      shutdown:
        await-termination: true
        await-termination-period: 30s
    execution:
      thread-name-prefix: "async-"
  application:
    name: spring-crud
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: true
      file: ${user.dir}/infrastructure/local/compose.yaml
      skip:
        in-tests: true
  datasource:
    hikari:
      pool-name: spring-crud-hikari-pool
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate.generate_statistics: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    # https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
    open-in-view: false
# Logging Properties
logging:
  level:
    root: INFO
# Actuator Properties
management:
  endpoints:
    web:
      exposure:
        include: "health, scheduledtasks, task, outbox"
# SpringDoc Properties
springdoc:
  show-actuator: true
  cache:
    disabled: true
