# Application Properties
application:
  outbox-relay:
    initial-delay: 30s
    fixed-delay: 10s
  scheduler:
    enabled: true
    initial-delay: 30s
    fixed-rate: 5s
    fixed-delay: 10
    cron: "0 * * * * *"
# Spring Properties
spring:
  task:
    scheduling:
      thread-name-prefix: "scheduler-"
      shutdown:
        await-termination: true
        await-termination-period: 30s
    execution:
      thread-name-prefix: "async-"
  application:
    name: spring-crud
  threads:
    virtual:
      enabled: true
  docker:
    compose:
      enabled: true
      file: ${user.dir}/infrastructure/local/compose.yaml
      skip:
        in-tests: true
  datasource:
    hikari:
      pool-name: spring-crud-hikari-pool
      maximum-pool-size: 10
  jpa:
    properties:
      # pretty print SQL statements
      hibernate.format_sql: true
      # generate JDBC statistics
      hibernate.generate_statistics: true
      # batching
      hibernate.jdbc.batch_size: 50
      # batch when doing inserts
      hibernate.order_inserts: true
      # batch when using @Version
      hibernate.batch_versioned_data: true
      # batch when doing updates
      hibernate.order_updates: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    # Detach JPA from the Spring HTTP request lifecycle
    open-in-view: false
# Logging Properties
logging:
  level:
    root: INFO
# Actuator Properties
management:
  endpoints:
    web:
      exposure:
        include: "health, scheduledtasks, task, outbox"
# SpringDoc Properties
springdoc:
  show-actuator: true
  cache:
    disabled: true
